# Generated by Django 5.2.3 on 2025-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('BS', 'Bác sĩ'), ('YT', 'Y tá'), ('DD', 'Điều dưỡng'), ('DS', 'Dược sĩ'), ('TT', 'Tiếp tân')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='position',
            field=models.CharField(choices=[('BS', 'Bác sĩ'), ('YT', 'Y tá'), ('DD', 'Điều dưỡng'), ('DS', 'Dược sĩ'), ('TT', 'Tiếp tân')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('BS', 'Bác sĩ'), ('YT', 'Y tá'), ('DD', 'Điều dưỡng'), ('DS', 'Dược sĩ'), ('TT', 'Tiếp tân')], max_length=2),
        ),
    ]
