# Generated by Django 5.2.3 on 2025-07-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('BS', 'Bác sĩ'), ('DD', 'Điều dưỡng'), ('DS', 'Dược sĩ'), ('TT', 'Tiếp tân')], max_length=2)),
                ('is_manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
