# Generated by Django 5.2.3 on 2025-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiayKhamBenh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieuDe', models.CharField(max_length=255)),
                ('tenBenhNhan', models.CharField(max_length=255)),
                ('theBHYT', models.BooleanField(default=False)),
                ('phongKham', models.CharField(max_length=255)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('bacSi', models.CharField(max_length=255)),
                ('ghiChu', models.TextField(blank=True)),
                ('ngayTao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
