# Generated by Django 5.2.3 on 2025-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
