# Generated by Django 5.2.3 on 2025-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_prescriptionmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('threshold', models.IntegerField(default=10)),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
